name: Run Script

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest
    environment: base_env
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.x'

    - name: Set up environment variables
      run: |
        echo "USDA_API_URL_TEMPLATE=https://api.ers.usda.gov/data/arms/surveydata?api_key=${{ secrets.USDA_API_KEY }}&year=2015&state=all&report=income+statement&farmtype=operator+households&category=collapsed+farm+typology&category_value=commercial" >> $GITHUB_ENV
        echo "USDA_API_KEY=${{ secrets.USDA_API_KEY }}" >> $GITHUB_ENV

    - name: Find requirements.txt
      id: find_requirements
      run: |
        REQUIREMENTS_PATH=$(find . -name 'requirements.txt' | head -n 1)
        if [[ -z "$REQUIREMENTS_PATH" ]]; then
          echo "requirements.txt not found"
          exit 1
        fi
        echo "REQUIREMENTS_PATH=${REQUIREMENTS_PATH}" >> $GITHUB_ENV
        echo "Found requirements at $REQUIREMENTS_PATH"

    - name: Install dependencies
      run: pip install -r $REQUIREMENTS_PATH

    - name: Find Python script
      id: find_script
      run: |
        SCRIPT_PATH=$(find . -name 'usda_arms_survey_data.py' | head -n 1)
        if [[ -z "$SCRIPT_PATH" ]]; then
          echo "usda_arms_survey_data.py not found"
          exit 1
        fi
        echo "SCRIPT_PATH=${SCRIPT_PATH}" >> $GITHUB_ENV
        echo "Found script at $SCRIPT_PATH"

    - name: Run script
      run: python $SCRIPT_PATH
